/**
 * Vercel Serverless Function — Nyati Elenor Lead Form Handler
 *
 * POST /api/submit-lead
 * Accepts lead form data and sends email notification to nomeshexponentia@gmail.com
 *
 * Environment variables required:
 *   SMTP_HOST  — SMTP server host (default: smtp.gmail.com)
 *   SMTP_PORT  — SMTP server port (default: 587)
 *   SMTP_USER  — SMTP username / email (sender)
 *   SMTP_PASS  — SMTP password or Gmail App Password
 *   NOTIFY_EMAIL — Recipient email (default: nomeshexponentia@gmail.com)
 *
 * For Gmail: Enable 2FA → Generate App Password at https://myaccount.google.com/apppasswords
 */

const nodemailer = require('nodemailer');

// CORS headers
const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
};

/**
 * Create transporter — reuses connection across warm invocations
 */
let transporter = null;

function getTransporter() {
  if (transporter) return transporter;

  transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST || 'smtp.gmail.com',
    port: parseInt(process.env.SMTP_PORT || '587', 10),
    secure: false,
    auth: {
      user: process.env.SMTP_USER || 'nomeshexponentia@gmail.com',
      pass: process.env.SMTP_PASS,
    },
  });

  return transporter;
}

/**
 * Format lead data into a professional HTML email
 */
function formatEmailHTML(data) {
  const fields = [
    { label: 'Project', value: data.project || 'Nyati Elenor' },
    { label: 'Name', value: data.name || 'Not provided' },
    { label: 'Email', value: data.email || 'Not provided' },
    { label: 'Phone', value: data.phone || 'Not provided' },
    { label: 'Configuration', value: data.configuration || 'Not specified' },
    { label: 'City', value: data.city || 'Not provided' },
    { label: 'Source', value: data.source || 'Landing Page' },
    { label: 'Date', value: new Date(data.timestamp).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }) || new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }) },
  ];

  const rows = fields
    .map(
      (f) => `
      <tr>
        <td style="padding: 10px 14px; border-bottom: 1px solid #e5e7eb; font-weight: 600; color: #134E4A; font-size: 13px; white-space: nowrap;">${f.label}</td>
        <td style="padding: 10px 14px; border-bottom: 1px solid #e5e7eb; color: #374151; font-size: 13px;">${f.value}</td>
      </tr>`
    )
    .join('');

  return `
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#F0FDFA;font-family:'Segoe UI',Arial,sans-serif;">
  <div style="max-width:560px;margin:0 auto;padding:30px 16px;">
    <!-- Header -->
    <div style="background:linear-gradient(135deg,#0F766E,#0C5E58);border-radius:16px 16px 0 0;padding:28px 24px;text-align:center;">
      <h1 style="color:#C9A84C;margin:0 0 4px;font-size:20px;letter-spacing:1px;">🔔 NEW LEAD</h1>
      <p style="color:#E8D5A3;margin:0;font-size:14px;">Nyati Elenor — Google Ads Landing Page</p>
    </div>

    <!-- Body -->
    <div style="background:#ffffff;border:1px solid #e5e7eb;border-top:0;padding:24px;">
      <table style="width:100%;border-collapse:collapse;">
        ${rows}
      </table>
    </div>

    <!-- Footer -->
    <div style="background:#134E4A;border-radius:0 0 16px 16px;padding:16px 24px;text-align:center;">
      <p style="color:#99F6E4;margin:0;font-size:11px;">
        📍 Lulla Nagar, South Pune · RERA: P52100078873
      </p>
      <p style="color:#5EEAD4;margin:4px 0 0;font-size:11px;">
        Auto-generated by Nyati Elenor Landing Page
      </p>
    </div>
  </div>
</body>
</html>`;
}

/**
 * Format a plain-text fallback email
 */
function formatEmailText(data) {
  return `
========================================
🔔 NEW LEAD — Nyati Elenor
========================================

Project:       ${data.project || 'Nyati Elenor'}
Name:          ${data.name || 'Not provided'}
Email:         ${data.email || 'Not provided'}
Phone:         ${data.phone || 'Not provided'}
Configuration: ${data.configuration || 'Not specified'}
City:          ${data.city || 'Not provided'}
Source:        ${data.source || 'Landing Page'}
Date:          ${new Date(data.timestamp).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }) || new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}

📍 Lulla Nagar, South Pune · RERA: P52100078873
========================================
`;
}

/**
 * Validate lead data
 */
function validate(data) {
  const errors = [];
  if (!data.name || data.name.trim().length < 2) errors.push('Name is required');
  if (!data.phone || data.phone.trim().length < 10) errors.push('Valid phone number is required');
  if (!data.email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email)) errors.push('Valid email is required');
  return errors;
}

// ─── Handler ───────────────────────────────────────────────────────────────

module.exports = async function handler(req, res) {
  // CORS preflight
  if (req.method === 'OPTIONS') {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // Parse body
  let data;
  try {
    data = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
  } catch {
    return res.status(400).json({ error: 'Invalid JSON body' });
  }

  // Validate
  const errors = validate(data);
  if (errors.length > 0) {
    return res.status(400).json({ error: 'Validation failed', details: errors });
  }

  try {
    const mailer = getTransporter();
    const recipient = process.env.NOTIFY_EMAIL || 'nomeshexponentia@gmail.com';

    await mailer.sendMail({
      from: `"Nyati Elenor Leads" <${process.env.SMTP_USER || 'nomeshexponentia@gmail.com'}>`,
      to: recipient,
      replyTo: data.email,
      subject: `🔔 New Lead: ${data.name} — ${data.configuration || 'Enquiry'} — Nyati Elenor`,
      text: formatEmailText(data),
      html: formatEmailHTML(data),
    });

    console.log(`✅ Lead from ${data.name} sent to ${recipient}`);
    return res.status(200).json({ success: true, message: 'Lead submitted successfully' });
  } catch (err) {
    console.error('Email send error:', err.message);

    // Still return 200 to the user — the form data is not lost
    // In production, you'd queue this for retry or log to a backup store
    return res.status(200).json({
      success: true,
      message: 'Lead received. Email notification pending.',
      warning: 'Email delivery delayed — team will be notified',
    });
  }
};
